#!/bin/sh
# autogenerated by train_people.py — exact retrain command
# commit None; dataset /home/zen/zensr-d7f16 (its meta.json embedded in model meta)
env ZENSR_DATA=/home/zen/zensr-d7f16 ZENSR_NC=8 ZENSR_NF=24 ZENSR_OUT=dejpeg_rt24g ZENSR_QBOOST=3 ZENSR_SCALE=1 python3 tools/train_people.py 200000 48 3e-4
